// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dlvuajspwgwdbyhczdra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRsdnVhanNwd2d3ZGJ5aGN6ZHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTcwMTUsImV4cCI6MjA3Mzk3MzAxNX0.13n5MG1S7n6qb8edGCLVLsIFJAhkCC5cBN4qZhKgGac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});